python3 preprocess.py  data/mono/vocab.en-fr.600 data/para/dev/newstest2013-ref.en.600  
python3 preprocess.py  data/mono/vocab.en-fr.600 data/para/dev/newstest2013-ref.fr.600  
python3 preprocess.py  data/mono/vocab.en-fr.600 data/para/dev/newstest2014-fren-src.en.600
python3 preprocess.py  data/mono/vocab.en-fr.600 data/para/dev/newstest2014-fren-src.fr.600





python3 marauderin.py --exp_name test --transformer True --n_enc_layers 4 --n_dec_layers 4 --share_enc 3 --share_dec 3 --share_lang_emb True --share_output_emb True --langs 'en,fr' --n_mono -1 --mono_dataset 'en:./data/mono/all.en.tok.600.pth,,;fr:./data/mono/all.fr.tok.600.pth,,' --para_dataset 'en-fr:,./data/para/dev/newstest2013-ref.XX.600.pth,./data/para/dev/newstest2014-fren-src.XX.600.pth' --mono_directions 'en,fr' --word_shuffle 3 --word_dropout 0.1 --word_blank 0.2 --pivo_directions 'fr-en-fr,en-fr-en' --lambda_xe_mono '0:1,100000:0.1,300000:0' --lambda_xe_otfd 1 --otf_num_processes 30 --otf_sync_params_every 1000 --enc_optimizer adam,lr=0.0001 --epoch_size 100 --stopping_criterion bleu_en_fr_valid,10

# supervised learning
# configurations

python3 main.py --exp_name test --transformer True --n_enc_layers 4 --n_dec_layers 4 --share_enc 3 --share_dec 3 --share_lang_emb False --share_output_emb False --langs 'x,y' --n_mono -1 --mono_dataset 'x:/home/abhinavds/Documents/Projects/NLP/SemanticParsing/cycle_gan/unpaired.x.pth,,;y:/home/abhinavds/Documents/Projects/NLP/SemanticParsing/cycle_gan/unpaired.y.pth,,' --n_para -1 --para_dataset 'x-y:/home/abhinavds/Documents/Projects/NLP/SemanticParsing/cycle_gan/paired.XX.pth,/home/abhinavds/Documents/Projects/NLP/SemanticParsing/cycle_gan/paired.XX.pth,/home/abhinavds/Documents/Projects/NLP/SemanticParsing/cycle_gan/paired.XX.pth'  --para_directions 'x-y' --mono_directions 'x,y' --word_shuffle 3 --word_dropout 0.1 --word_blank 0.2 --pivo_directions 'x-y-x,y-x-y' --lambda_xe_mono '0:1,100000:0.1,300000:0'  --lambda_xe_para '0:1,100000:0.1,300000:0'  --lambda_xe_otfd 1 --otf_num_processes 30 --otf_sync_params_every 1000 --enc_optimizer adam,lr=0.0001 --epoch_size 500 --stopping_criterion bleu_x_y_valid,10 --cudnn_enabled False

python3 main.py --exp_name test --transformer True --n_enc_layers 4 --n_dec_layers 4 --share_enc 3 --share_dec 3 --share_lang_emb False --share_output_emb False --langs 'x,y' --n_mono -1 --mono_dataset 'x:/home/abhinavds/Documents/Projects/NLP/SemanticParsing/cycle_gan/unpaired.x.pth,,;y:/home/abhinavds/Documents/Projects/NLP/SemanticParsing/cycle_gan/unpaired.y.pth,,' --n_para -1 --para_dataset 'x-y:/home/abhinavds/Documents/Projects/NLP/SemanticParsing/cycle_gan/paired.XX.pth,/home/abhinavds/Documents/Projects/NLP/SemanticParsing/cycle_gan/paired.XX.pth,/home/abhinavds/Documents/Projects/NLP/SemanticParsing/cycle_gan/paired.XX.pth' --para_directions 'x-y, y-x' --pivo_directions 'x-y-x,y-x-y'   --lambda_xe_para '0:1,100000:0.1,300000:0'  --lambda_xe_otfd 1 --lambda_dis 0.5 --n_dis 2 --otf_num_processes 30 --otf_sync_params_every 1000 --enc_optimizer adam,lr=0.0001 --epoch_size 500 --stopping_criterion bleu_x_y_valid,10 --cudnn_enabled False



# Unpaired and paired dataset (THIS ONE!!!!)
python3 main.py --exp_name test --exp_id results --transformer True --n_enc_layers 4 --n_dec_layers 4 --share_enc 3 --share_dec 3 --share_lang_emb False --share_output_emb False --langs 'x,y' --n_mono -1 --mono_dataset 'x:/home/abhinavds/Documents/Projects/NLP/SemanticParsing/cycle_gan/unpaired.x.pth,,;y:/home/abhinavds/Documents/Projects/NLP/SemanticParsing/cycle_gan/unpaired.y.pth,,' --n_para -1 --para_dataset 'x-y:/home/abhinavds/Documents/Projects/NLP/SemanticParsing/cycle_gan/paired.XX.pth,/home/abhinavds/Documents/Projects/NLP/SemanticParsing/cycle_gan/paired.XX.pth,/home/abhinavds/Documents/Projects/NLP/SemanticParsing/cycle_gan/paired.XX.pth' --mono_directions 'x,y' --word_shuffle 3 --word_dropout 0.1 --word_blank 0.2 --para_directions 'x-y,y-x' --pivo_directions 'x-y-x,y-x-y'   --lambda_xe_mono '0:1,100000:0.1,300000:0' --lambda_xe_para '0:1,100000:0.1,300000:0'  --lambda_xe_otfd 1 --lambda_dis 0.5 --n_dis 2 --otf_num_processes 30 --otf_sync_params_every 1000 --enc_optimizer adam,lr=0.0001 --epoch_size 500 --stopping_criterion bleu_x_y_valid,10 --cudnn_enabled False



# Supervised only on paired dataset (with back translation loss)
python3 main.py --exp_name config_mined_100_0 --exp_id results --dump_path /home/marauder/ut/nlp_cs388/final_proj/nmt/ --transformer False --n_enc_layers 4 --n_dec_layers 4 --share_enc 3 --share_dec 3 --share_lang_emb False --share_output_emb False --langs 'x,y' --n_mono -1  --mono_dataset 'x:/home/marauder/ut/nlp_cs388/final_proj/nmt/config_mined_100_0/data/para.x.pth,,;y:/home/marauder/ut/nlp_cs388/final_proj/nmt/config_mined_100_0/data/para.y.pth,,' --n_para -1 --para_dataset 'x-y:/home/marauder/ut/nlp_cs388/final_proj/nmt/config_mined_100_0/data/para.XX.pth,/home/marauder/ut/nlp_cs388/final_proj/nmt/config_mined_100_0/data/conala-dev.XX.pth,/home/marauder/ut/nlp_cs388/final_proj/nmt/config_mined_100_0/data/conala-test.XX.pth' --para_directions 'x-y,y-x' --pivo_directions 'x-y-x,y-x-y'   --lambda_xe_para '0:1,100000:0.1,300000:0'  --lambda_xe_otfd 1 --lambda_dis 0.5 --n_dis 2 --otf_num_processes 30 --otf_sync_params_every 1000 --enc_optimizer adam,lr=0.0001 --epoch_size -1 --stopping_criterion bleu_x_y_valid,10


python3 preprocess.py --data-dir ../../conala-clean/ --out-dir ../../nmt/ --name tr_50_0 --file-info "conala-trainnodev,50,0" --dev conala-dev --test conala-test

python3 preprocess.py --data-dir ../../conala-clean/ --out-dir ../../nmt/ --name tr_50_0_m_0_17 --file-info "conala-trainnodev,50,0,conala-mined,0,17" --dev conala-dev --test conala-test

# Supervised
python3 main.py --exp_name tr_50_0 --exp_id results --dump_path /scratch/cluster/ankgarg/nlp/nmt/ --transformer False --n_enc_layers 4 --n_dec_layers 4 --share_enc 3 --share_dec 3 --share_lang_emb False --share_output_emb False --langs 'x,y' --n_mono -1  --mono_dataset 'x:/scratch/cluster/ankgarg/nlp/nmt/tr_50_0/data/para.x.pth,,;y:/scratch/cluster/ankgarg/nlp/nmt/tr_50_0/data/para.y.pth,,' --n_para -1 --para_dataset 'x-y:/scratch/cluster/ankgarg/nlp/nmt/tr_50_0/data/para.XX.pth,/scratch/cluster/ankgarg/nlp/nmt/tr_50_0/data/conala-dev.XX.pth,/scratch/cluster/ankgarg/nlp/nmt/tr_50_0/data/conala-test.XX.pth' --para_directions 'x-y,y-x' --pivo_directions 'x-y-x,y-x-y'   --lambda_xe_para '0:1,100000:0.1,300000:0'  --lambda_xe_otfd 1 --lambda_dis 0.5 --n_dis 2 --otf_num_processes 10 --otf_sync_params_every 1000 --enc_optimizer adam,lr=0.0001 --epoch_size -1 --stopping_criterion bleu_x_y_valid,25 --batch_size 32 --max_epoch 200

# Semi-supervised
python3 main.py --exp_name tr50_50 --exp_id results --dump_path /scratch/cluster/ankgarg/nlp/nmt/ --transformer False --n_enc_layers 4 --n_dec_layers 4 --share_enc 3 --share_dec 3 --share_lang_emb False --share_output_emb False --langs 'x,y' --n_mono -1  --mono_dataset 'x:/scratch/cluster/ankgarg/nlp/nmt/tr50_50/data/mono.x.pth,,;y:/scratch/cluster/ankgarg/nlp/nmt/tr50_50/data/mono.y.pth,,' --n_para -1 --para_dataset 'x-y:/scratch/cluster/ankgarg/nlp/nmt/tr50_50/data/para.XX.pth,/scratch/cluster/ankgarg/nlp/nmt/tr50_50/data/conala-dev.XX.pth,/scratch/cluster/ankgarg/nlp/nmt/tr50_50/data/conala-test.XX.pth' --para_directions 'x-y,y-x' --pivo_directions 'x-y-x,y-x-y' --mono_directions 'x,y' --word_shuffle 3 --word_dropout 0.1 --word_blank 0.2   --lambda_xe_mono '0:1,100000:0.1,300000:0'  --lambda_xe_para '0:1,100000:0.1,300000:0'  --lambda_xe_otfd 1 --lambda_dis 0.5 --n_dis 2 --otf_num_processes 10 --otf_sync_params_every 1000 --enc_optimizer adam,lr=0.0001 --epoch_size -1 --stopping_criterion bleu_x_y_valid,25 --batch_size 32 --max_epoch 200

python3 main.py --exp_name tr_50_0_m_0_17e-2 --exp_id results --dump_path /scratch/cluster/ankgarg/nlp/nmt/ --transformer False --n_enc_layers 4 --n_dec_layers 4 --share_enc 3 --share_dec 3 --share_lang_emb False --share_output_emb False --langs 'x,y' --n_mono -1  --mono_dataset 'x:/scratch/cluster/ankgarg/nlp/nmt/tr_50_0_m_0_17e-2/data/mono.x.pth,,;y:/scratch/cluster/ankgarg/nlp/nmt/tr_50_0_m_0_17e-2/data/mono.y.pth,,' --n_para -1 --para_dataset 'x-y:/scratch/cluster/ankgarg/nlp/nmt/tr_50_0_m_0_17e-2/data/para.XX.pth,/scratch/cluster/ankgarg/nlp/nmt/tr_50_0_m_0_17e-2/data/conala-dev.XX.pth,/scratch/cluster/ankgarg/nlp/nmt/tr_50_0_m_0_17e-2/data/conala-test.XX.pth' --para_directions 'x-y,y-x' --pivo_directions 'x-y-x,y-x-y' --mono_directions 'x,y' --word_shuffle 3 --word_dropout 0.1 --word_blank 0.2   --lambda_xe_mono '0:1,100000:0.1,300000:0'  --lambda_xe_para '0:1,100000:0.1,300000:0'  --lambda_xe_otfd 1 --lambda_dis 0.5 --n_dis 2 --otf_num_processes 10 --otf_sync_params_every 1000 --enc_optimizer adam,lr=0.0001 --epoch_size -1 --stopping_criterion bleu_x_y_valid,25 --batch_size 32 --max_epoch 200

CUDA_VISIBLE_DEVICES=1 python3 main.py --exp_name tr_100_0_m_0_10 --exp_id results --dump_path /scratch/cluster/ankgarg/nlp/nmt/ --transformer True --n_enc_layers 4 --n_dec_layers 4 --share_enc 3 --share_dec 3 --share_lang_emb False --share_output_emb False --langs 'x,y' --n_mono -1  --mono_dataset 'x:/scratch/cluster/ankgarg/nlp/nmt/tr_100_0_m_0_10/data/mono.x.pth,,;y:/scratch/cluster/ankgarg/nlp/nmt/tr_100_0_m_0_10/data/mono.y.pth,,' --n_para -1 --para_dataset 'x-y:/scratch/cluster/ankgarg/nlp/nmt/tr_100_0_m_0_10/data/para.XX.pth,/scratch/cluster/ankgarg/nlp/nmt/tr_100_0_m_0_10/data/conala-dev.XX.pth,/scratch/cluster/ankgarg/nlp/nmt/tr_100_0_m_0_10/data/conala-test.XX.pth' --para_directions 'x-y,y-x' --pivo_directions 'x-y-x,y-x-y' --mono_directions 'x,y' --word_shuffle 3 --word_dropout 0.1 --word_blank 0.2   --lambda_xe_mono '0:1,100000:0.1,300000:0'  --lambda_xe_para '0:1,100000:0.1,300000:0'  --lambda_xe_otfd 1 --lambda_dis 0.5 --n_dis 2 --otf_num_processes 1 --otf_sync_params_every 100 --enc_optimizer adam,lr=0.0001 --epoch_size -1 --stopping_criterion bleu_x_y_valid,25 --cudnn_enabled True --batch_size 32  --max_epoch 2 